name: Release

on:
  push:
    tags:
      - '*'

jobs:
  docker-build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.platform }} - ${{ matrix.browser }} - ${{ matrix.tag }}
    strategy:
      matrix:
        include:
          # Chromium - x86
          - runner: 'buildjet-4vcpu-ubuntu-2204'
            tag: 'latest'
            platform: 'amd64'
            browser: 'chromium'
            goss: 'goss-linux-amd64'

          # Chromium - ARM
          - runner: 'buildjet-4vcpu-ubuntu-2204-arm'
            tag: 'arm'
            platform: 'linux/arm64'
            browser: 'chromium'
            goss: 'goss-linux-arm'

          # Chrome - x86
          - runner: 'buildjet-4vcpu-ubuntu-2204'
            tag: 'chrome'
            platform: 'amd64'
            browser: 'chrome'
            goss: 'goss-linux-amd64'

          # Chrome - ARM (Chrome is not available for ARM)
          #- runner: "buildjet-4vcpu-ubuntu-2204-arm"
          #  tag: "chrome-arm"
          #  platform: "linux/arm64"
          #  browser: "chrome"
          #  goss: 'goss-linux-arm'

          # No browser - x86
          - runner: 'buildjet-4vcpu-ubuntu-2204'
            tag: 'noweb'
            platform: 'amd64'
            browser: 'none'
            goss: 'goss-linux-amd64'

          # No browser - ARM
          - runner: 'buildjet-4vcpu-ubuntu-2204-arm'
            tag: 'noweb-arm'
            platform: 'linux/arm64'
            browser: 'none'
            goss: 'goss-linux-arm'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4a6ae47374b4490eb851b5ec915153ea }}/devwpwa:${{ github.sha }}
          file: ./Dockerfile
